[build]
  functions = "functions-build"
  command = "yarn build"
  publish = "public"
  environment = { NODE_VERSION = "14.17.0" }

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200